// src/components/Block.tsx
import React from 'react';
import './scss/Block.scss';
import MaskedText from './MaskedText';

interface BlockProps {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
  className?: string;
}

function Block(props: BlockProps): JSX.Element {
  const id = props.title.toLowerCase().replace(' ', '-');

  return (
    <div id={id} className={'block ' + (props.className ?? '')}>
      <h1 className="block__title">{props.title}</h1>
      <MaskedText>{props.subtitle}</MaskedText>
      {props.children}
      {/* <div className="block__background"></div> */}
    </div>
  );
}

export default Block;

// portfolio/src/lib/components/Block.svelte
<script lang="ts">
  import MaskedText from '$lib/components/MaskedText.svelte';

  export let title: string;
  export let subtitle: string = '';
  export let className: string = '';

  if (className === '') {
    className = title.toLowerCase().replace(' ', '-');
  }
</script>

<div id="{title.toLowerCase().replace(' ', '-')}" class="block__{className}">
  <h1 class="block__title">{title}</h1>
  <MaskedText>{subtitle}</MaskedText>
  <slot />
</div>
