// portfolio/src/routes/about/+page.svelte
<script lang="ts">
  import Block from '$lib/components/Block.svelte';
  import SubBlock from '$lib/components/SubBlock.svelte';
</script>

<Block title="About">
  <SubBlock title="University" subtitle="University of Technology">
    Currently working as a freelance software developer, I have worked on
    several projects, both web and mobile, using different technologies.
  </SubBlock>
  <SubBlock title="Skills" subtitle="University of Technology">
    Currently working as a freelance software developer, I have worked on
    several projects, both web and mobile, using different technologies.
  </SubBlock>
  <SubBlock title="Interests" subtitle="University of Technology">
    Currently working as a freelance software developer, I have worked on
    several projects, both web and mobile, using different technologies.
  </SubBlock>
</Block>

// src/layout/content/About.tsx
import React from 'react';
import Block from '../../components/Block';

/**
 * @desc This is the About component
 * @returns {JSX.Element} The About component
 */
function About(props: { className?: string }): JSX.Element {
  return (
    <Block title="About" className={props.className}>
      <div className="about__education">
        <h2>Education</h2>
        <p>
          Currently working as a freelance software developer, I have worked on
          several projects, both web and mobile, using different technologies.
        </p>
      </div>
      <div className="about__skills">
        <h2>Skills</h2>
        <p>
          Currently working as a freelance software developer, I have worked on
          several projects, both web and mobile, using different technologies.
        </p>
      </div>
      <div className="about__interests">
        <h2>Interests</h2>
        <p>
          Currently working as a freelance software developer, I have worked on
          several projects, both web and mobile, using different technologies.
        </p>
      </div>
    </Block>
  );
}

export default About;
