// src/lib/components/Description.svelte
<script lang="ts">
	import Block from '$components/Block.svelte';
	import { t, json, isLoading } from 'svelte-i18n';

	$: description = $json('page.about.me.description') as string[];
</script>

<Block title="Daniel Hernández de León" subtitle={$t('page.about.me.job')} id="home">
	{#if $isLoading}
		<p>Loading...</p>
	{:else if description.length === 0}
		<p>No data</p>
	{:else}
		{#each description as line}
			<p>{line}</p>
		{/each}
	{/if}
</Block>

// src/layout/content/Description.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import './scss/Description.scss';
import Block from '../../components/Block';

function Description(props: { className?: string }): JSX.Element {
  const { t } = useTranslation();
  const text1 = t('summary_1');
  const text2 = t('summary_2');
  // const elements = text1.map((line) => <li key={line}><p>{line}</p></li>);
  const elements = [text1, text2].map((line) => (
    <li key={line}>
      <p>{line}</p>
    </li>
  ));
  const subtitle = t('software');

  return (
    <Block
      title="Daniel Hernández de León"
      subtitle={subtitle}
      className={props.className}
    >
      <ul className={'description__summary'}>{elements}</ul>
    </Block>
  );
}

export default Description;
