// portfolio/src/routes/projects/+page.svelte
<script lang="ts">
  import Block from '$lib/components/Block.svelte';
  import SubBlock from '$lib/components/SubBlock.svelte';
</script>

<Block title="Projects">
  <SubBlock title="Project 1" subtitle="Freelance">
    Currently working as a freelance software developer, I have worked on
    several projects, both web and mobile, using different technologies.
  </SubBlock>
  <SubBlock title="Project 2" subtitle="Freelance">
    Currently working as a freelance software developer, I have worked on
    several projects, both web and mobile, using different technologies.
  </SubBlock>
  <SubBlock title="Project 3" subtitle="Freelance">
    Currently working as a freelance software developer, I have worked on
    several projects, both web and mobile, using different technologies.
  </SubBlock>
</Block>

// src/layout/content/Projects.tsx
import React from 'react';
import Block from '../../components/Block';

/**
 * @desc This is the Projects component
 * @returns {JSX.Element} The Projects component
 */
function Projects(props: { className?: string }): JSX.Element {
  return (
    <Block title="Projects" className={props.className}>
      <div className="project">
        <h2>Project 1</h2>
        <p>
          Currently working as a freelance software developer, I have worked on
          several projects, both web and mobile, using different technologies.
        </p>
      </div>
      <div className="project">
        <h2>Project 2</h2>
        <p>
          Currently working as a freelance software developer, I have worked on
          several projects, both web and mobile, using different technologies.
        </p>
      </div>
      <div className="project">
        <h2>Project 3</h2>
        <p>
          Currently working as a freelance software developer, I have worked on
          several projects, both web and mobile, using different technologies.
        </p>
      </div>
    </Block>
  );
}

export default Projects;
