// src/layout/Footer.tsx
import React from 'react';
import './scss/Footer.scss';

/**
 * @desc This is the main Footer component
 * @returns {JSX.Element} The main Footer component
 */
function Footer(): JSX.Element {
  return (
    <footer id="footer">
      <div>
        <p>+34 603 66 69 13</p>
      </div>
      <div>
        <a href="mailto:daniel@danielhrdez.dev?subject=Hello%20Daniel!">
          <p>daniel@danielhrdez.dev</p>
        </a>
      </div>
      <div>
        <a
          href="https://www.linkedin.com/in/danielhrdez/"
          target="_blank"
          rel="noreferrer"
        >
          <p>Linkedin</p>
        </a>
      </div>
    </footer>
  );
}

export default Footer;

// src/lib/components/Footer.svelte
<footer
	class="
  flex
  h-10
  justify-around
  items-center
  bg-neutral-100
  dark:bg-neutral-600
"
>
	<div>
		<p>+34 603 66 69 13</p>
	</div>
	<div>
		<a href="mailto:daniel@danielhrdez.dev?subject=Hello%20Daniel!">
			<p>daniel@danielhrdez.dev</p>
		</a>
	</div>
	<div>
		<a href="https://www.linkedin.com/in/danielhrdez/" target="_blank" rel="noreferrer">
			<p>Linkedin</p>
		</a>
	</div>
</footer>

<style lang="postcss">
	a {
		text-decoration: none;
		color: var(--neutral-900);
	}

	div {
		@apply bg-transparent dark:bg-transparent;
	}
</style>
