// portfolio/src/lib/components/Header.svelte
<script lang="ts">
  import danielPng from '$lib/images/daniel.png';
  import settingsIcon from '$lib/images/settings-btn.svg';

  function disableScroll(): void {
    const htmlBody = document.querySelector('html, body') as HTMLElement;
    if (htmlBody === null) {
      throw new Error('The html or body tag is not found');
    }
    htmlBody.style.overflow = 'hidden';
  }

  function settingsExpand(): void {
    document.querySelector('.settings')?.classList.add('show');
    disableScroll();
  };
</script>

<header class="flex justify-around p-1">
  <img src={danielPng} alt="daniel" class="w-10" />
  <nav class="flex justify-around items-center container">
    <a href="/">Home</a>
    <a href="/tech">Technologies</a>
    <a href="/experience">Experience</a>
    <a href="/academic">Academic</a>
    <a href="/projects">Projects</a>
  </nav>
  <button on:click={settingsExpand}>
    <img src={settingsIcon} alt="settings" class="w-6" />
  </button>
</header>

// src/layout/Header.tsx
import React, { useState } from 'react';
import { ReactComponent as SettingsButton } from '../assets/images/settings-btn.svg';
import './scss/Header.scss';
import me from '../assets/images/me.webp';
import { disableScroll } from '../utils/scrollFunctions';
import HeaderLink from '../components/HeaderLink';
import language from '../utils/language';

/**
 * @desc This is the main Header component
 * @returns {JSX.Element} The main Header component
 */
function Header(): JSX.Element {
  const settingsExpand = (): void => {
    document.querySelector('.settings')?.classList.add('show');
    disableScroll();
  };
  const [activeLink, setActiveLink] = useState(language('Home'));
  const handleLinkClick = (link: string): void => {
    setActiveLink(link);
  };
  const links = [
    { href: '#content', text: language('Home') },
    { href: '#about', text: language('About') },
    { href: '#experiences', text: language('Experience') },
    { href: '#projects', text: language('Projects') },
    { href: '#footer', text: language('Contact') },
  ];
  return (
    <header className="header">
      <img className="header__image" src={me} alt="me" />
      <nav className="header__nav-links">
        {links.map((link) => (
          <HeaderLink
            key={link.text}
            href={link.href}
            text={link.text}
            active={link.text === activeLink}
            onClick={handleLinkClick}
          />
        ))}
      </nav>
      <SettingsButton className="header__settings" onClick={settingsExpand} />
    </header>
  );
}

export default Header;
